# Generated by Django 3.2.9 on 2021-11-22 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_configuration_data'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_traceback', models.TextField()),
                ('model_type', models.CharField(max_length=25, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('model_content', models.TextField()),
                ('operation', models.CharField(max_length=1, null=True)),
                ('registration_datetime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.data')),
            ],
        ),
        migrations.CreateModel(
            name='application_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_traceback', models.TextField()),
                ('model_type', models.CharField(max_length=25, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('model_content', models.TextField()),
                ('operation', models.CharField(max_length=1, null=True)),
                ('registration_datetime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('company_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.data')),
            ],
        ),
    ]
